### ISSUE TITLE
It crashed

### ISSUE THREAD

**Issue by Kaylathefurry** [xstabux/Omaloon#40]
![image](https://github.com/xstabux/Omaloon/assets/161249080/175a7895-087e-4915-a0dd-e169c41898df)

**Comment by xstabux** [comment]
can you provide the full crash report file please?

**Comment by Kaylathefurry** [comment]
sure gimme a sec

**Comment by Kaylathefurry** [comment]
[crash-report-02_25_2024_20_23_43.txt](https://github.com/xstabux/Omaloon/files/14409814/crash-report-02_25_2024_20_23_43.txt)
that's it right? (idk what else to give)

**Comment by xstabux** [comment]
As for the old version of Omaloon, which is currently in the mod browser...
Currently, that Omaloon works correctly, but using some mods with it you may get a game crash. I am not going to fix this bug for several reasons:
1. The code is outdated and I can't really make changes to old content.
2. That Omaloon has no actual value because it is only suitable for sandbox games.
Thank you for your understanding
